### PR TITLE
Improve and Document Testing

### PR DESCRIPTION
**Pull request by ppmdo**
Currently, the project has testing settings at cab/tests/settings.py which are completely independent from the main project settings.
This might lead to tests running on a different setup and also complicate maintenance as settings are scattered.

I managed to "re-create" testing settings under the main project settings folder. These import the base settings and just override certain values. 

When doing this, I noticed that the project has some standalone django apps which have their own independent tests. This leads a bit of complication because ROOT_URLCONF and some base templates have to be overridden for those tests to work. Therefore, tests actually work with different templates than those used in production:

Overridden settings:
https://github.com/django/djangosnippets.org/blob/792a3cf3f0da6c6ce0bea3fa941533712ce1dff7/cab/tests/tests.py#L12-L16
https://github.com/django/djangosnippets.org/blob/792a3cf3f0da6c6ce0bea3fa941533712ce1dff7/ratings/tests/tests.py#L34-L45

Different base templates:
https://github.com/django/djangosnippets.org/blob/792a3cf3f0da6c6ce0bea3fa941533712ce1dff7/cab/tests/settings.py#L54-L56

Taken from these files:
https://github.com/django/djangosnippets.org/tree/792a3cf3f0da6c6ce0bea3fa941533712ce1dff7/cab/tests/templates

I don't really know what to do with those cases, so please any thoughts welcome!

I think the tests should focus on the main djangosnippets code. We could either disable the independent tests, have those apps packaged separately or at least document that tests are running which such complicated setup.

### CODE REVIEW

**Comment by chriswedgwood** [comment]
Thanks @ppmdo 🙏 will take a look. It does sound like a bit of a mess to untangle 👍

**Comment by ppmdo** [comment]
@chriswedgwood, I haven't configured any of those before. Any preference on which one to use?

**Comment by chriswedgwood** [comment]
> @chriswedgwood, I have never configured any of those before. Any preference on which one to use?

@ppmdo  I have already set github actions  ci on the upstream main. If you sync/merge/rebase your fork with that it should kick off in the PR

**Comment by ppmdo** [comment]
Great. I have merged main.

Regarding the "independent" testing of cab.tests and ratings.tests, do you have any ideas on how we should proceed?

**Comment by chriswedgwood** [comment]
> Great. Thanks for that. I have merged main.
> 
> Regarding the "independent" testing of cab.tests and ratings.tests, do you have any ideas on how we should proceed?

I think any test that is not running against a template used in production should be changed to use the production template.

**Review by chriswedgwood — APPROVED** [review]

**Comment by chriswedgwood** [comment]
@ppmdo  I have added an extra check on PR's to run on pull_request.

If you fetch upstream again the CI should run in the PR.

I had a look on your repo and the CI is failing with flake8 issues 

https://github.com/ppmdo/djangosnippets.org/runs/2889448668

**Comment by ppmdo** [comment]
@chriswedgwood I've marked all the tests that are not using production templates for skipping and fixed the issue with flake8.

I don't really like skipping tests but I think that if those modules need independent testing with different base templates, probably they should be packaged separately with their own tests.

In the meantime, I think this allows development to proceed without depending on any special tricks on the test suite.

**Pull request merged**
