### PR TITLE
Full Text url, views and form 

### PR DESCRIPTION
**Pull request by chriswedgwood**
This introduces a set of urls that have  a suffix of full_text that handle search using full text search within postgres.
Non-functional changes that exist in this PR are in order to pass all the tests using postgres.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @chriswedgwood. Thanks for this. Django 3.1 today, so ... 😀 Give me a couple of days to get to it.

**Comment by chriswedgwood** [comment]
> Hi @chriswedgwood. Thanks for this. Django 3.1 today, so ... 😀 Give me a couple of days to get to it.



> Hi @chriswedgwood. Thanks for this. Django 3.1 today, so ... 😀 Give me a couple of days to get to it.

No sweat 👍

**Comment by carltongibson** [comment]
Hi @chriswedgwood. 

I've just been chatting to @MarkusH because I was worried (not quite the right word but let's go with it 🙂) about if we break something with the deploy. 

Current PostgreSQL is 9.5, which is when FTS was introduced, but one good thing to do would be to upgrade Postgres (to say 12) before pulling this in, just a good hygiene thing. You have access right? Is that something you fancy working on. (I think Heroku have a good guide for this.) 

Then, I'll review over the next few days, and we should just merge it and see: the new stuff is on the new URLs so... — all should be good. Then we can move the new search implementation across to the old URLs once we're happy.

**Comment by chriswedgwood** [comment]
> Hi @chriswedgwood.
> 
> I've just been chatting to @MarkusH because I was worried (not quite the right word but let's go with it 🙂) about if we break something with the deploy.
> 
> Current PostgreSQL is 9.5, which is when FTS was introduced, but one good thing to do would be to upgrade Postgres (to say 12) before pulling this in, just a good hygiene thing. You have access right? Is that something you fancy working on. (I think Heroku have a good guide for this.)
> 
> Then, I'll review over the next few days, and we should just merge it and see: the new stuff is on the new URLs so... — all should be good. Then we can move the new search implementation across to the old URLs once we're happy.

Hi @carltongibson  , yes I have access and will be happy to upgrade postgres to 12 before we merge this. Will report back here when done. 👍

**Comment by MarkusH** [comment]
> Hi @carltongibson , yes I have access and will be happy to upgrade postgres to 12 before we merge this. Will report back here when done. +1

Hey @chriswedgwood feel free to ping me or "ops AT djangoproject DOT com" if you run into trouble.

**Comment by chriswedgwood** [comment]
Thanks Markus 🙏

**Pull request merged**
